### ISSUE TITLE
job.get_nodes() does not split to individual cores for Torque-5.x

### ISSUE THREAD

**Issue by itkovian** [radik/pbs-python#1]
In Torque 4.x, the exec_host string is following the format

```
node1/0+node1/1+node1/2+node2/0+node2/1+...
```

This means that the get_nodes function will yield a list of individual node/core items. However, in Torque 5.x, the information provided by qstat (and thus what ps_python's PBSQuery.job picks up) is using the more dense format

```
$ qstat -f1 9915.master19.golett.gent.vsc | grep exec
exec_host = node2400.golett.gent.vsc/0-23+node2432.golett.gent.vsc/0-23+node2444.golett.gent.vsc/0-23+node2446.golett.gent.vsc/0-23+node2452.golett.gent.vsc/0-23+node2454.golett.gent.vsc/0-23+node2456.golett.gent.vsc/0-23
```

This will yield a list with items 'node2400/0-23', which is not listing the individual node/core like before.

Could we have a flag that allows us to further split on a per-core basis? Would you accept a PR for that?

**Comment by radik** [comment]
I'm not maintainer of the package source code. I've just created pip package for [pbs_python](http://oss.trac.surfsara.nl/pbs_python).
Please, contact with package author Bas van der Vlies (bas.vandervlies@surfsara.nl).
